### ISSUE TITLE
Add update instructions for 1-click deployments

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk-site#41]
https://listmonk.app/docs/upgrade/

Re: https://github.com/knadh/listmonk-site/pull/23

I'm assuming that for Railway and the likes, a simple redeployment will do, but that has to be tested...

**Comment by knadh** [comment]
Hi @candideu. I'm not sure how PikaPods, Railway etc. do upgrades. If you are able to figure out, please do share it so that we can add it to the docs.
