### ISSUE TITLE
Add link to GitHub?

### ISSUE THREAD

**Issue by melroy89** [knadh/listmonk-site#43]
In the about section of GitHub you could add a website link to the actual live deployment?

https://listmonk.app/

![image](https://user-images.githubusercontent.com/628926/219514076-12ca8841-5a0f-473f-8935-f79b0389deda.png)

Why not 👍🏽 ?

**Comment by knadh** [comment]
Done. I do want to archive this repository entirely and move the contents to a `docs` folder on the `knadh/listmonk` repository soon.

**Comment by melroy89** [comment]
or split the archive in front page and the docs in `knadh/listmonk`?
