### ISSUE TITLE
Technical writer

### ISSUE THREAD

**Issue by Quadrisheriff** [knadh/listmonk-site#5]
Hi Knadh, my name is Quadri Sheriff and i will like to help in writing listmonk's documentation.
I have already created a PR for subscriber and lists resource but there are some endpoints that are creating issues for me and ill like us to discuss about.

**Comment by knadh** [comment]
@Quadrisheriff apologies for a second time. I missed all the PRs on this repo. And thank you, again, for the excellent PRs!
