### ISSUE TITLE
Subscriber facing and static views 

### ISSUE THREAD

**Issue by Quadrisheriff** [knadh/listmonk-site#8]
Hi knadh, I have been trying to create docs for the last two routes, namely the subscriber facing views, and the  static views.

However, I think your input will be needed to better document this routes. I can't really infer much from the code comments. 

You should also check out all the endpoints that I have not yet documented in the other routes. They are probably not working as intended in their comments or not working at all.

**Comment by knadh** [comment]
Hi @Quadrisheriff They are non-API routes that render HTML pages like the unsubscribe page. I don't think you need to document them along with the API endpoints. Nonetheless, I've just improved the comments on those handlers here https://github.com/knadh/listmonk/commit/c9fc83fb60b4d99cf623bdf0f0360b39117fdda3.

I'll check out the excluded endpoints and figure out what's wrong. Thanks!
